service: paramiko-py38

provider:
  name: aws
  profile: jb
  region: ${opt:region, 'eu-central-1'}

layers:
  paramiko:
    path: build
    name: paramiko-py38
    description: Provides Paramiko SSH library for Python
    compatibleRuntimes:
      - python3.8
    allowedAccounts:
      - '*'
    retain: true
